### PR TITLE
getOutput superseded by returnStdout

### PR DESCRIPTION
**Pull request by jglick**
As of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/11 (plugin version 2.4), `getOutput` is unnecessary.

@reviewbybees (for my colleagues)

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by mikedougherty** [comment]
These changes LGTM -- should I wait on a @reviewbybees review?

**Comment by jglick** [comment]
> should I wait on a @reviewbybees review?

You need not.

**Comment by oleg-nenashev** [comment]
🐝 anyway
@reviewbybees done

**Pull request merged**
