### PR TITLE
print what exception is caught

### PR DESCRIPTION
**Pull request by andrewhsu**
in case the chown fails, want to know what happened

### CODE REVIEW

**Comment by andrewhsu** [comment]
@mikedougherty

**Comment by mikedougherty** [comment]
change is fine, i'm just not sure it will be helpful enough -- i think the only info that will give is the exit code of the command. if that's not enough, a quick idea i just had is to add `-v` to the chown command, pipe to a file so as not to fill the log every time, and then cat the file on failure.

**Comment by andrewhsu** [comment]
For now i think it is good enough to just have an error code. It will greatly help diagnosis with very little impact.

**Comment by mikedougherty** [comment]
👍

**Pull request merged**
